version: '3.10'
services:
  db:
    container_name: mysql_db
    platform: linux/x86_64
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    restart: unless-stopped
    
  api:
    depends_on:
      - db
    container_name: flask_api
    platform: linux/x86_64
    build:
       context: ./myapi
       dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./myapi:/app
    ports:
      - "8000:80"
    env_file:
      - ./myapi/.env
      
  web:
    depends_on:
      - api
    container_name: vite-web
    platform: linux/x86_64
    build:
       context: ./Aeroclub-Lincoln
       dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:5173
    env_file:
      - ./Aeroclub-Lincoln/.env.local
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "8080:80"

volumes:
  mysql-data: